added new feature: broken package; removed useless get_file; removed skip_pkg function

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -22,6 +22,8 @@
 export TEXTDOMAIN='repoman'
 export TEXTDOMAINDIR='/usr/share/locale'
 
+declare -a pkgs repopkgsver repopkgsrel brokenpkgs ignorepkgs uptodatepkgs
+
 colors(){
   if [ "$NOCOLOR" != "TRUE" ]; then
     DEFA="\033[1;0m"
@@ -36,16 +38,12 @@ colors(){
 
 print_addpkg_error(){
   printf "$(gettext "failed! Cannot add %s to repository.") ${LRED}$(gettext "Skip.\n")${DEFA}" "$1"
-  skip_pkg $1
+  brokenpkgs[${#brokenpkgs[@]}]=$1
 }
 
 print_cannotgetfile_error(){
   printf "${LRED}$(gettext "Cannot get %s. Skip.")${DEFA}" "$1"
-  if [ "$1" == "$repo.db.tar.gz" ]; then
-    printf "${LRED}$(gettext "\nI cannot continue without the database repo file. Exit.\n")${DEFA}"
-    exit 1
-  fi
-  skip_pkg $1
+  brokenpkgs[${#brokenpkgs[@]}]=$1
 }
 
 print_makepkg_error(){
@@ -54,31 +52,17 @@ print_makepkg_error(){
 
 print_removepkg_error(){
   printf "$(gettext "failed! Cannot remove %s from repository.") ${LRED}$(gettext "Skip.\n")${DEFA}" "$1"
-  skip_pkg $1
+  brokenpkgs[${#brokenpkgs[@]}]=$1
 }
 
 print_tar_error(){
   printf "${LRED}$(gettext "Extraction failed! Skip.\n")${DEFA}"
-  skip_pkg $1
+  brokenpkgs[${#brokenpkgs[@]}]=$1
 }
 
 print_upload_error(){
   printf "${LRED}$(gettext "failed! Cannot upload %s.\n")${DEFA}" "$1"
-  skip_pkg $1
-}
-
-get_file(){
-  printf "${LGRE}$1 ${DEFA}"
-  mv "${workspace}/$1" "${workspace}/$1.old" &> /dev/null
-  if [ "$LOCAL" != "TRUE" ]; then
-    if [ "$VERBOSE" == "TRUE" ]; then
-      wget -P "${workspace}" "$url/$1" || print_cannotgetfile_error $1
-    else
-      wget -P "${workspace}" "$url/$1" &> /dev/null || print_cannotgetfile_error $1
-    fi
-  else
-    cp "$url/$repo.db.tar.gz" "${workspace}/" || exit 1
-  fi
+  brokenpkgs[${#brokenpkgs[@]}]=$1
 }
 
 extract_pkg(){
@@ -91,23 +75,23 @@ extract_pkg(){
     fi
   else
     printf "$(gettext "tarball not found. Skip\n")"
-    skip_pkg $1
+    brokenpkgs[${#brokenpkgs[@]}]=$1
   fi
 }
 
-skip_pkg(){
-  for i in ${!pkgs[@]}; do
-    if [ "${pkgs[$i]}" == "$1" ]; then
-      pkgs[$i]=""
-      pkgsver[$i]=""
-    fi
+# $1 = package
+# $2 = array
+pkg_in_array(){
+  for pkg in ${2}; do
+    if [ "${1}" == "${pkgname}" ]; then return 0; else return 1; fi
   done
+  return 1
 }
 
 build_pkg(){
   [ "$EDIT" == "TRUE" ] && edit_pkgbuild $1
 
-  cd ${workspace}/pkgs/$1 && source PKGBUILD || skip_pkg $1
+  cd ${workspace}/pkgs/$1 && source PKGBUILD || brokenpkgs[${#brokenpkgs[@]}]=$1
   pkgsver[$INDEX]="$pkgver-$pkgrel"
 
   printf "$1: "
@@ -127,7 +111,7 @@ build_pkg(){
       fi
 
       #this is needed to update pkgver/pkgrel in case of devel package
-      source PKGBUILD || skip_pkg $1
+      source PKGBUILD || brokenpkgs[${#brokenpkgs[@]}]=$1
       pkgsver[$INDEX]="$pkgver-$pkgrel"
 
       if [ -f ${workspace}/pkgs/$1/$1-${pkgsver[$INDEX]}-*.pkg.tar.gz ]; then
@@ -135,7 +119,7 @@ build_pkg(){
         printf "${LGRE}${pkgsver[$INDEX]} $(gettext "done")${DEFA}"
         (( UPDATED ++ ))
       else
-        skip_pkg $1
+        brokenpkgs[${#brokenpkgs[@]}]=$1
       fi
     else
       printf "${LGRE}$(gettext "done, already built")${DEFA}"
@@ -143,7 +127,7 @@ build_pkg(){
     fi
   else
     printf "${YELL}$(gettext "skip, already up-to-date")${DEFA}"
-    skip_pkg $1
+    uptodatepkgs[${#uptodatepkgs[@]}]=$1
   fi
 }
 
@@ -171,9 +155,14 @@ update(){
     printf "$changelog "
     rm -f /tmp/header "/tmp/$changelog"
     INDEX=0
+    BROKEN="FALSE"
     for pkg in ${pkgs[@]}; do
-      echo "* `date +\"%d-%m-%Y %R\"` `whoami` $FLAG$pkg ${pkgsver[$INDEX]}" >> /tmp/header
-      (( INDEX++ ))
+      if `pkg_in_array $pkg $pkgs`; then BROKEN="TRUE"; fi
+      if [ "$BROKEN" != "TRUE" ]; then
+        echo "* `date +\"%d-%m-%Y %R\"` `whoami` $FLAG$pkg ${pkgsver[$INDEX]}" >> /tmp/header
+        (( INDEX++ ))
+      fi
+      BROKEN="FALSE"
     done
     cat /tmp/header "${workspace}/$changelog" > "/tmp/$changelog"
     mv "/tmp/$changelog" "${workspace}/$changelog"
@@ -283,7 +272,7 @@ check_args(){
           devel) DEVEL="TRUE"; ADD="TRUE"; FORCE="TRUE" ;;
           force) FORCE="TRUE" ;;
           ignore) shift $(($OPTIND - 1))
-            ignorepkg=`echo $1 | tr ',' ' '`
+            ignorepkgs=`echo $1 | tr ',' ' '`
             shift
             OPTIND=1 ;;
           keep) KEEP="TRUE" ;;
@@ -351,7 +340,7 @@ get_pkgbuild(){
     printf "$(gettext "(keeping PKGBUILD)\n")"
   else
     printf "$(gettext "PKGBUILD not found. Skip\n")"
-    skip_pkg $1
+    brokenpkgs[${#brokenpkgs[@]}]=$1
   fi
 }
 
@@ -412,11 +401,16 @@ upload(){
   remove_from_ftp $pkg
   if [ "$ADD" == "TRUE" ]; then
     INDEX=0
+    BROKEN="FALSE"
     for pkg in ${pkgs[@]}; do
-      printf "Uploading $pkg ${pkgsver[$INDEX]}..."
-      upload_file $pkg-${pkgsver[$INDEX]}-*.pkg.tar.gz || print_upload_error $pkg-${pkgsver[$INDEX]}
-      printf "\n"
-      (( INDEX++ ))
+      if `pkg_in_array $pkg $pkgs`; then BROKEN="TRUE"; fi
+      if [ "$BROKEN" != "TRUE" ]; then
+        printf "Uploading $pkg ${pkgsver[$INDEX]}..."
+        upload_file $pkg-${pkgsver[$INDEX]}-*.pkg.tar.gz || print_upload_error $pkg-${pkgsver[$INDEX]}
+        printf "\n"
+        (( INDEX++ ))
+      fi
+      BROKEN="FALSE"
     done
   elif [ "$REMOVE" == "TRUE" ]; then
     printf "$(gettext "All copy of %s have been removed from ftp!\n")" "$pkg"
@@ -441,26 +435,22 @@ get_pkgs_list(){
   IGNORE="FALSE"
   if [ "$DEVEL" == "TRUE" ]; then
     for pkg in `tar -tf "${workspace}/$repo.db.tar.gz" | grep -vE 'desc$|depends$' | sed -e 's:\/$::g' | grep "\-\(svn\|cvs\|hg\|git\|bzr\|darcs\)"`; do
-      for ipkg in ${ignorepkg[@]}; do
-        pkgname=`echo $pkg | rev | cut -d'-' -f3- | rev`
-        [ "${ipkg}" == "${pkgname}" ] && IGNORE="TRUE"
-      done
+      local pkgname=`echo $pkg | rev | cut -d'-' -f3- | rev`
+      if `pkg_in_array $pkgname $ignorepkgs`; then IGNORE="TRUE"; fi
       if [ "$IGNORE" != "TRUE" ]; then
-        pkgs[${#pkgs[@]}]=`echo $pkg | rev | cut -d'-' -f3- | rev`
+        pkgs[${#pkgs[@]}]=$pkgname
         repopkgsver[${#repopkgsver[@]}]=`echo $pkg | rev | cut -d'-' -f2 | rev`
         repopkgsrel[${#repopkgsrel[@]}]=`echo $pkg | rev | cut -d'-' -f1 | rev`
       fi
       IGNORE="FALSE"
     done
   else
-    printf "${BOLD}$(gettext "This will update the whole repository!\n")${DEFA}"
+    printf "${YELL}$(gettext "This will update the whole repository!\n")${DEFA}"
     for pkg in `tar -tf "${workspace}/$repo.db.tar.gz" | grep -vE 'desc$|depends$' | sed -e 's:\/$::g'`; do
-      for ipkg in ${ignorepkg[@]}; do
-        pkgname=`echo $pkg | rev | cut -d'-' -f3- | rev`
-        [ "${ipkg}" == "${pkgname}" ] && IGNORE="TRUE"
-      done
+      local pkgname=`echo $pkg | rev | cut -d'-' -f3- | rev`
+      if `pkg_in_array $pkgname $ignorepkgs`; then IGNORE="TRUE"; fi
       if [ "$IGNORE" != "TRUE" ]; then
-        pkgs[${#pkgs[@]}]=`echo $pkg | rev | cut -d'-' -f3- | rev`
+        pkgs[${#pkgs[@]}]=$pkgname
         repopkgsver[${#repopkgsver[@]}]=`echo $pkg | rev | cut -d'-' -f2 | rev`
         repopkgsrel[${#repopkgsrel[@]}]=`echo $pkg | rev | cut -d'-' -f1 | rev`
       fi
@@ -479,10 +469,29 @@ main(){
   colors
 
   if [ "$CREATE" != "TRUE" ]; then
-    printf "${YELL}$(gettext "Getting: ")${DEFA}"
-    [ "$NOCHANGELOG" != "TRUE" ] && get_file $changelog
-    get_file $repo.db.tar.gz
-    printf "\n"
+    printf "${YELL}$(gettext "Getting: ")${LGRE}${changelog} ${repo}.db.tar.gz${DEFA}\n"
+    mv "${workspace}/${changelog}" "${workspace}/${changelog}.old" &> /dev/null
+    mv "${workspace}/${repo}.db.tar.gz" "${workspace}/${repo}.db.tar.gz.old" &> /dev/null
+    if [ "$LOCAL" != "TRUE" ]; then
+      if [ "$VERBOSE" == "TRUE" ]; then
+        [ "$NOCHANGELOG" != "TRUE" ] && wget -P "${workspace}" "$url/${changelog}" \
+          || printf "${LRED}$(gettext "Cannot get %s\n${DEFA}")" ${changelog}
+        wget -P "${workspace}" "$url/${repo}.db.tar.gz" \
+          || printf "${LRED}$(gettext "Cannot get %s\n${DEFA}")" ${repo}.db.tar.gz
+        printf "\n"
+      else
+        [ "$NOCHANGELOG" != "TRUE" ] && wget -P "${workspace}" "$url/${changelog}" &> /dev/null \
+          || printf "${LRED}$(gettext "Cannot get %s\n${DEFA}")" ${changelog}
+        wget -P "${workspace}" "$url/${repo}.db.tar.gz" &> /dev/null \
+          || printf "${LRED}$(gettext "Cannot get %s\n${DEFA}")" ${repo}.db.tar.gz
+      fi
+    else
+      cp "$url/${changelog}" "${workspace}/" &> /dev/null
+      cp "$url/${repo}.db.tar.gz" "${workspace}/" &> /dev/null
+    fi
+
+    [ ! -f "${workspace}/${changelog}" ] && exit 1
+    [ ! -f "${workspace}/${repo}.db.tar.gz" ] && exit 1
   fi
 
   [ "$ALL" == "TRUE" -o "$DEVEL" == "TRUE" ] && get_pkgs_list
@@ -511,14 +520,19 @@ main(){
     printf "${YELL}$(gettext "Building: ")${DEFA}"
     UPDATED=0
     INDEX=0
+    BROKEN="FALSE"
     for pkg in ${pkgs[@]}; do
-      build_pkg $pkg
-      (( INDEX++ ))
-      printf "\n"
+      if `pkg_in_array $pkg $pkgs`; then BROKEN="TRUE"; fi
+      if [ "$BROKEN" != "TRUE" ]; then
+        build_pkg $pkg
+        (( INDEX++ ))
+        printf "\n"
+      fi
+      BROKEN="FALSE"
     done
   fi
   
-  if [[ "$UPDATED" -ne "0" ]] || [ "$REMOVE" == "TRUE" ]; then
+  if [[ "$UPDATED" -gt "0" ]] || [ "$REMOVE" == "TRUE" ]; then
     printf "${YELL}$(gettext "Updating: ")${DEFA}"
     update
     if [ "$NOUPLOAD" != "TRUE" ]; then
@@ -526,14 +540,14 @@ main(){
     elif [ "$LOCAL" == "TRUE" ]; then
       copy_files
     fi
-  else
-    printf "$(gettext "None packages added to repository\n")"
-    exit 1
+
+    if [ "$NOCONFIRM" != "TRUE" ]; then
+      [ "$ADD" == "TRUE" ] && ask_remove
+    fi
   fi
-  
-  if [ "$NOCONFIRM" != "TRUE" ]; then
-    [ "$ADD" == "TRUE" ] && ask_remove 
-  fi
+
+  [[ "${#brokenpkgs[@]}" -gt "0" ]] && printf "$(gettext "Broken package: %s\n")" ${brokenpkgs[@]}
+#  [[ "${#uptodatepkgs[@]}" -gt "0" ]] && printf "$(gettext "Up-to-date package: %s\n")" ${uptodatepkgs[@]}
 }
 
 main $@
