added error messages

diff --git a/repoman b/repoman
--- a/repoman
+++ b/repoman
@@ -42,18 +42,32 @@ function color()
   fi
 }
 
+function print_wget_error()
+{
+  printf "\n${LRED}I can't get $1. Exiting. ${DEFA}\n"
+  exit 1
+}
+
+function print_tar_error()
+{
+  printf "\n${LRED}I can't extract $1. Exiting. ${DEFA}\n"
+  exit 1
+}
+
+function print_makepkg_error()
+{
+  printf "\n${LRED}Makepkg fail. Exiting. ${DEFA}\n"
+  exit 1
+}
+
 function get_file()
 {
   printf "${LGRE} $1 ${DEFA}"
   rm -f $workspace/$1
   if [ "$VERBOSE" = "TRUE" ]; then
-    wget -P $workspace $url/$1
+    wget -P $workspace $url/$1 || print_wget_error $1
   else
-    wget -P $workspace $url/$1 &> /dev/null
-  fi
-  if [ ! -f $workspace/$1 ]; then
-    printf "\n${LRED}I can't get $1. Exiting. ${DEFA}\n"
-    exit 0
+    wget -P $workspace $url/$1 &> /dev/null || print_wget_error $1
   fi
 }
 
@@ -61,13 +75,9 @@ function get_pkg()
 {
   printf "${LGRE} $1.tar.gz ${DEFA}"
   if [ "$VERBOSE" = "TRUE" ]; then
-    wget -P $workspace/pkg http://aur.archlinux.org/packages/$1/$1.tar.gz
+    wget -P $workspace/pkg http://aur.archlinux.org/packages/$1/$1.tar.gz || print_wget_error $1
   else
-    wget -P $workspace/pkg http://aur.archlinux.org/packages/$1/$1.tar.gz &> /dev/null
-  fi
-  if [ ! -f $workspace/pkg/$1.tar.gz ]; then
-    printf "\n${LRED}I don't find $1. Exiting. ${DEFA}\n"
-    exit 0
+    wget -P $workspace/pkg http://aur.archlinux.org/packages/$1/$1.tar.gz &> /dev/null || print_wget_error $1
   fi
 }
 
@@ -75,7 +85,7 @@ function extract()
 {
   printf "${LGRE}$1 ${DEFA}"
   rm -rf $workspace/pkg/$1
-  tar -xf $workspace/pkg/$1.tar.gz -C $workspace/pkg || return 1
+  tar -xf $workspace/pkg/$1.tar.gz -C $workspace/pkg || print_tar_error $1
 
 }
 
@@ -98,16 +108,16 @@ function build_pkg()
   pkgrel=`cat PKGBUILD | grep pkgrel= | awk -F'=' '{print $2}'`
   pkgver=`echo $pkgver-$pkgrel`
   if [ "$VERBOSE" = "TRUE" ]; then
-    makepkg -f --noconfirm $NOCOLOR_FLAG || return 1
+    makepkg -f --noconfirm $NOCOLOR_FLAG || print_makepkg_error
   else
-    makepkg -f --noconfirm $NOCOLOR_FLAG &> /dev/null || return 1
+    makepkg -f --noconfirm $NOCOLOR_FLAG &> /dev/null || print_makepkg_error
   fi
   printf " ($pkgver)${DEFA}\n"
 }
 
 function copy_pkg()
 {
-  cp $workspace/pkg/$1/$1-$pkgver-$arch.pkg.tar.gz $workspace/
+  cp $workspace/pkg/$1/$1-$pkgver-$arch.pkg.tar.gz $workspace/ || exit 1
 }
 
 function update_db()
@@ -115,16 +125,16 @@ function update_db()
   printf "${YELL}Updating: ${LGRE}$repo.db.tar.gz${DEFA}\n"
   if [ "$action" = "add" ] || [ "$action" = "update" ]; then
     if [ "$VERBOSE" = "TRUE" ]; then
-      repo-add $workspace/$repo.db.tar.gz $workspace/$1-$pkgver-$arch.pkg.tar.gz || return 1
+      repo-add $workspace/$repo.db.tar.gz $workspace/$1-$pkgver-$arch.pkg.tar.gz || exit 1
     else
-      repo-add $workspace/$repo.db.tar.gz $workspace/$1-$pkgver-$arch.pkg.tar.gz &> /dev/null || return 1
+      repo-add $workspace/$repo.db.tar.gz $workspace/$1-$pkgver-$arch.pkg.tar.gz &> /dev/null || exit 1
     fi
   elif [ "$action" = "remove" ]; then
     printf "${LGRE}$1 ${YELL}deleted! ${DEFA}\n"
     if [ "$VERBOSE" = "TRUE" ]; then
-      repo-remove $workspace/$repo.db.tar.gz $1 || return 1
+      repo-remove $workspace/$repo.db.tar.gz $1 || exit 1
     else
-      repo-remove $workspace/$repo.db.tar.gz $1 &> /dev/null || return 1
+      repo-remove $workspace/$repo.db.tar.gz $1 &> /dev/null || exit 1
     fi
   fi
 }
